Added an additional line to add a latest.json file

diff --git a/nubis/puppet/files/consul-backup b/nubis/puppet/files/consul-backup
--- a/nubis/puppet/files/consul-backup
+++ b/nubis/puppet/files/consul-backup
@@ -41,5 +41,11 @@ if [[ -s $BACKUP_FILE ]]; then
         $LOGGER "Error: RV value is ${RV}, and unable to copy ${BACKUP_FILE_NAME} to s3 bucket"
     fi
 
+    $LOGGER "Copying latest.json to s3 (BucketName: ${BACKUP_BUCKET})"
+    aws s3 cp $BACKUP_FILE s3://${BACKUP_BUCKET}/latest.json --region ${REGION} --quiet
+    RV=$?
+    if [[ $RV -ne 0 ]]; then
+        $LOGGER "Error: RV value is ${RV}, and unable to copy latest.json to s3 bucket"
+    fi
 
 fi
